export const typeInfos = {
  bug: { fr: 'Insecte', color: '#729f3f' },
  dark: { fr: 'Ténèbres', color: '#707070' },
  dragon: { fr: 'Dragon', color: 'linear-gradient(180deg, #53a4cf 50%, #f16e57 50%)' },
  electric: { fr: 'Électrik', color: '#eed535' },
  fairy: { fr: 'Fée', color: '#fdb9e9' },
  fighting: { fr: 'Combat', color: '#d56723' },
  fire: { fr: 'Feu', color: '#fd7d24' },
  flying: { fr: 'Vol', color: 'linear-gradient(180deg, #3dc7ef 50%, #bdb9b8 50%)' },
  ghost: { fr: 'Spectre', color: '#7b62a3' },
  grass: { fr: 'Plante', color: '#9dca5d' },
  ground: { fr: 'Sol', color: 'linear-gradient(180deg, #f7de3f 50%, #ab9842 50%)' },
  ice: { fr: 'Glace', color: '#51c4e7' },
  normal: { fr: 'Normal', color: '#a4acaf' },
  poison: { fr: 'Poison', color: '#b97fc9' },
  psychic: { fr: 'Psy', color: '#f366b9' },
  rock: { fr: 'Roche', color: '#a38c21' },
  shadow: { fr: 'Ombre', color: '#0e2e4c' },
  steel: { fr: 'Acier', color: '#9eb7b8' },
  water: { fr: 'Eau', color: '#4592c4' },
}
