/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Detailstestbeforeenglishswap: typeof import('./components/detailstestbeforeenglishswap.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    PokemonDetails: typeof import('./components/PokemonDetails.vue')['default']
    PokemonDetailsSkeleton: typeof import('./components/PokemonDetailsSkeleton.vue')['default']
    PokemonDetailsTest: typeof import('./components/PokemonDetailsTest.vue')['default']
    PokemonList: typeof import('./components/PokemonList.vue')['default']
    PokemonTest: typeof import('./components/PokemonTest.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Testbeforebed: typeof import('./components/testbeforebed.vue')['default']
    Testbeforeenglishswap: typeof import('./components/testbeforeenglishswap.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
  }
}
